-- Persist Shopping Search product-group operating recommendations for saved planning runs.
-- This stores planning metadata only; it does not create, update, delete, or activate Naver product groups.

create table if not exists public.planning_product_groups (
  id uuid primary key default gen_random_uuid(),
  planning_run_id uuid not null references public.planning_runs(id) on delete cascade,
  name text not null,
  source_group text not null,
  query_count integer not null default 0,
  product_hints text[] not null default '{}'::text[],
  feed_actions text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

alter table public.planning_product_groups enable row level security;

create index if not exists planning_product_groups_run_idx
  on public.planning_product_groups(planning_run_id, query_count desc);

comment on table public.planning_product_groups is
  'Read-only Shopping Search product-group recommendations generated by the MVP planner and shown in saved history.';
